version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./public/static:/static
      - ./public/media:/media
      - ./conf/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mysecretpassword'
    volumes:
      - ./db:/var/lib/postgresql/data

  web:
    restart: always
    build: .
#    command: bash -c 'python manage.py makemigrations && python manage.py migrate && python manage.py filldicts --fill && python manage.py sitetree_resync_apps && gunicorn src.wsgi -b 0.0.0.0:8000'
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && gunicorn src.wsgi -b 0.0.0.0:8000'
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
