# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': ' Классы обучения',
                'verbose_name': 'Класс обучения',
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': ' Возрастные группы',
                'verbose_name': 'Возрастная группа',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='HealthStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Состояния здоровья',
                'verbose_name': 'Состояние здоровья',
                'db_table': 'health_states',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Дошкольное'), (1, 'Школьное')], null=True, verbose_name='Тип учреждения')),
            ],
            options={
                'verbose_name_plural': ' Учреждения',
                'verbose_name': 'Учреждение',
                'db_table': 'institutions',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Населенные пункты',
                'verbose_name': 'Населенный пункт',
                'db_table': 'locality',
            },
        ),
        migrations.CreateModel(
            name='ParentsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': ' Статусы родителей(семьи)',
                'verbose_name': 'Статус родителей',
                'db_table': 'parents_status',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Улицы',
                'verbose_name': 'Улица',
                'db_table': 'streets',
            },
        ),
    ]
