# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Класс обучения',
                'verbose_name_plural': ' Классы обучения',
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Возрастная группа',
                'verbose_name_plural': ' Возрастные группы',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GuideFamilyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Многодетные'), (2, 'Малоимущие'), (3, 'Неполные'), (4, 'КМНС')])),
            ],
            options={
                'verbose_name': 'Статус семьи',
                'verbose_name_plural': ' Статус семьи',
                'db_table': 'guide_status',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Дошкольное'), (1, 'Школьное')], null=True, verbose_name='Тип учреждения')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': ' Учреждения',
                'db_table': 'institutions',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
                'db_table': 'locality',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'db_table': 'streets',
            },
        ),
    ]
