# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('position', models.IntegerField(default=0, verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='DictionariesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('position', models.IntegerField(default=0, verbose_name='Очередность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип справочника',
                'verbose_name_plural': 'Типы справочников',
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('institution_type', models.IntegerField(blank=True, choices=[(0, 'Дошкольное'), (1, 'Школьное')], null=True, verbose_name='Тип учреждения')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.DictionariesType', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'db_table': 'dictionaries',
            },
        ),
    ]
