# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('position', models.IntegerField(default=0, verbose_name='Очередность')),
            ],
            options={
                'db_table': 'param',
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ParamHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('risk_group', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], verbose_name='Группа риска')),
                ('note', models.CharField(max_length=256, verbose_name='Сосотяние')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_grade', to='dictionaries.Dictionary', verbose_name='Класс')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_group', to='dictionaries.Dictionary', verbose_name='Группа')),
                ('health_states', models.ManyToManyField(blank=True, null=True, related_name='history_health_states', to='dictionaries.Dictionary', verbose_name='Состояние здоровья')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_institution', to='dictionaries.Dictionary', verbose_name='Учреждение')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Param', verbose_name='Параметр')),
                ('parents_status', models.ManyToManyField(blank=True, null=True, related_name='history_parents_status', to='dictionaries.Dictionary', verbose_name='Статус семьи')),
            ],
            options={
                'db_table': 'param_history',
                'verbose_name': 'Истории параметров',
                'verbose_name_plural': 'История параметров',
                'ordering': ['-first_date', '-last_date'],
            },
        ),
    ]
