# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20160811_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramhistory',
            name='health_states',
            field=models.ManyToManyField(blank=True, related_name='history_health_states', to='dictionaries.Dictionary', verbose_name='Состояние здоровья'),
        ),
        migrations.AlterField(
            model_name='paramhistory',
            name='parents_status',
            field=models.ManyToManyField(blank=True, related_name='history_parents_status', to='dictionaries.Dictionary', verbose_name='Статус семьи'),
        ),
    ]
