# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='Очередность')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Dictionary', unique=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name_plural': 'Шаги',
                'verbose_name': 'Шаг',
                'db_table': 'steps',
            },
        ),
    ]
