# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['position'], 'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.AlterField(
            model_name='step',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Dictionary', unique=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='step',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
    ]
