# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='Дата рождения')),
                ('house', models.CharField(blank=True, max_length=4, null=True, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, max_length=4, null=True, verbose_name='Квартира')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality', to='dictionaries.Locality', verbose_name='Населенный пункт')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='street', to='dictionaries.Street', verbose_name='Улица')),
            ],
            options={
                'verbose_name_plural': 'Дети',
                'verbose_name': 'Ребенок',
                'db_table': 'children',
            },
        ),
    ]
