# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality', to='parameters.Locality', verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='child',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='street', to='parameters.Street', verbose_name='Улица'),
        ),
    ]
