# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_auto_20160914_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='child',
            unique_together=set([]),
        ),
    ]
