# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Классы обучения общего образования',
                'db_table': 'classes',
                'verbose_name': 'Класс обучения общего образования',
            },
        ),
        migrations.CreateModel(
            name='EducationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Возрастные группы дошкольного образования',
                'db_table': 'groups',
                'verbose_name': 'Возрастная группа дошкольного образования',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Дошкольное'), (1, 'Школьное')], null=True, verbose_name='Тип учреждения')),
            ],
            options={
                'verbose_name_plural': 'Учреждения',
                'db_table': 'institutions',
                'verbose_name': 'Учреждение',
            },
        ),
    ]
