# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('educations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
            ],
            options={
                'db_table': 'family_status',
                'verbose_name_plural': 'Статусы семьи',
                'verbose_name': 'Статус семьи',
            },
        ),
        migrations.CreateModel(
            name='GuideFamilyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(1, 'Многодетные'), (2, 'Малоимущие'), (3, 'Неполные'), (4, 'КМНС')], max_length=16)),
            ],
            options={
                'db_table': 'guide_status',
                'verbose_name_plural': 'Справочник статуса семьи',
                'verbose_name': 'Справочник статуса семьи',
            },
        ),
        migrations.CreateModel(
            name='HealthHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('text', models.CharField(max_length=128, verbose_name='Сосотяние')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
            ],
            options={
                'db_table': 'healths',
                'verbose_name_plural': 'Здоровье',
                'verbose_name': 'Здоровье',
            },
        ),
        migrations.CreateModel(
            name='NoteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('text', models.CharField(max_length=256, verbose_name='Сосотяние')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
            ],
            options={
                'db_table': 'notes',
                'verbose_name_plural': 'Примечания',
                'verbose_name': 'Примечание',
            },
        ),
        migrations.CreateModel(
            name='RiskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('group', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')])),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
            ],
            options={
                'db_table': 'risks',
                'verbose_name_plural': 'Группа риска',
                'verbose_name': 'Группа риска',
            },
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educations.Grade', verbose_name='Класс')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educations.Group', verbose_name='Группа')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educations.Institution', verbose_name='Учреждение')),
            ],
            options={
                'db_table': 'students',
                'verbose_name_plural': 'Ученики',
                'verbose_name': 'Ученик',
            },
        ),
        migrations.AddField(
            model_name='familystatushistory',
            name='status',
            field=models.ManyToManyField(to='parameters.GuideFamilyStatus'),
        ),
    ]
