# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
                ('status', models.ManyToManyField(to='dictionaries.GuideFamilyStatus')),
            ],
            options={
                'verbose_name': 'Истории статусов семей',
                'verbose_name_plural': 'История статуса семьи',
                'db_table': 'family_status',
            },
        ),
        migrations.CreateModel(
            name='HealthHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('text', models.CharField(max_length=128, verbose_name='Сосотяние')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Истории состояния здоровья',
                'verbose_name_plural': 'История состояния здоровья',
                'db_table': 'healths',
            },
        ),
        migrations.CreateModel(
            name='NoteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('text', models.CharField(max_length=256, verbose_name='Сосотяние')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Истории примечаний',
                'verbose_name_plural': 'История примечаний',
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='RiskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('group', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], verbose_name='Группа риска')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Группа риска',
                'verbose_name_plural': 'Группа риска',
                'db_table': 'risks',
            },
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(default=datetime.datetime.now, verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child', verbose_name='Ребенок')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Grade', verbose_name='Класс')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Group', verbose_name='Группа')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Institution', verbose_name='Учреждение')),
            ],
            options={
                'verbose_name': 'Истории обучения',
                'ordering': ['-first_date', '-last_date'],
                'verbose_name_plural': 'История обучения',
                'db_table': 'students',
            },
        ),
    ]
