# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthistory',
            options={'verbose_name': 'Учащийся', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='guidefamilystatus',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Многодетные'), (2, 'Малоимущие'), (3, 'Неполные'), (4, 'КМНС')]),
        ),
    ]
