# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthistory',
            options={'ordering': ['first_date', 'last_date'], 'verbose_name': 'Истории обучения', 'verbose_name_plural': 'История обучения'},
        ),
    ]
