# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('kids', '0001_initial'),
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(verbose_name='Начальная дата')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('education_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.EducationClass')),
                ('education_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.EducationGroup')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.Kid', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Ученик',
                'db_table': 'students',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
