# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_auto_20160408_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskhistory',
            name='group',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], verbose_name='Группа риска'),
        ),
    ]
