# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_studenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='education_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.EducationClass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='education_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.EducationGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution', verbose_name='Учреждение'),
        ),
    ]
